#配置端口号
server:
  port: 8888

#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_music?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #项目启动时初始化DispatchServlet，-1为不启动，正数为启动
  mvc:
    servlet:
      load-on-startup: 1

mybatis:
# 配置实体类目录
  type-aliases-package: com.gyr.music.entity
  #mapper路径
  mapper-locations: classpath:mapper/*.xml


